# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

#
# SSL
#
http:
  server_port: !secret server_port
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# ssl_profile: intermediate

#
# Google assistant
#
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include google-service-account.json
  exposed_domains:
    - sensor
    - light
    - script
    - scene

# cors_allowed_origins:
#   - https://google.com
#   - https://www.home-assistant.io

#
# Living room remote
#
remote:
  - platform: broadlink
    name: Living Room Remote
    mac: !secret living_room_remote_mac
    host: !secret living_room_remote_host

#
# Triones LED strips (my custom platform)
#
my_platform:
  - name: "TV Backlight"
    type: triones
    mac: !secret tv_backlight_mac
  - name: "Other strip"
    type: triones
    mac: !secret other_strip_mac
    #  - name: "Demo Light"
    #    type: triones
    #    mac: 88:ff:bc:00:2b:09

tv_service:

device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 30
    new_device_defaults:
      track_new_devices: false
    hosts:
      keirans_phone: 10.0.0.30

#
# Binary sensors
#
binary_sensor:
  - platform: ping
    name: Big TV
    scan_interval: 30
    count: 2
    host: 10.0.0.43

#
# Customize
#
homeassistant:
  customize:
    binary_sensor.big_tv:
      icon: mdi:television-classic
      friendly_name: Big TV
      device_class: power
    # person.keiran:
    #   entity_picture: /local/person.png

#
# Logging configuration
#
logger:
  default: info
  logs:
    custom_components.my_platform: debug
    custom_components.tv_service: debug

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
