default_config:

homeassistant:
  packages:
    deck: !include packages/deck/fairy_lights.yaml
    default: !include packages/default.yaml
    device_tracker: !include packages/device_tracker.yaml
    home: !include packages/home.yaml
    lighting: !include packages/lighting/lighting.yaml
    my_platform: !include packages/my_platform.yaml
    tv: !include packages/tv/tv.yaml
    ui: !include packages/ui/ui.yaml
