default_config:

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
    - type: homeassistant

  packages:
    deck: !include packages/deck/fairy_lights.yaml
    default: !include packages/default.yaml
    home: !include packages/home.yaml
    network: !include packages/network.yaml
    lighting: !include packages/lighting/lighting.yaml
    effects: !include packages/lighting/effects.yaml
    # my_platform: !include packages/my_platform.yaml
    # presence: !include packages/presence.yaml
    # security: !include packages/security.yaml
    tv: !include packages/tv/tv.yaml
    ui: !include packages/ui/ui.yaml
