# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

# homeassistant:
#   customize:
#     person.keiran:
#       entity_picture: /local/person.png

# http:
#   server_port: 8123
#   base_url: !secret base_url
#   ip_ban_enabled: true
#   login_attempts_threshold: 10
#   ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
#   ssl_key: /home/homeassistant/.homeassistant/privkey.pem

# google_assistant:
#   project_id: home-assistant-c6eef
#   api_key: !secret google_app_key
#   service_account: !include google-service-account.json
#   exposed_domains:
#     - sensor
#     - light
#   entity_config:
#     light.television_lighting:
#       expose: true
#       room: LIVING_ROOM

# ssl_profile: intermediate
# cors_allowed_origins:
#   - https://google.com
#   - https://www.home-assistant.io

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


#
# Living room remote
#
remote:
  - platform: broadlink
    name: Living Room Remote
    mac: !secret living_room_remote_mac
    host: !secret living_room_remote_host

#
# Triones LED strips (my custom platform)
#
my_platform:
  - name: "TV Backlight"
    type: triones
    mac: !secret tv_backlight_mac
  - name: "Other strip"
    type: triones
    mac: !secret other_strip_mac
    #  - name: "Demo Light"
    #    type: triones
    #    mac: 88:ff:bc:00:2b:09

device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 30
    new_device_defaults:
      track_new_devices: false
    hosts:
      keirans_phone: 10.0.0.30

#
# Logging configuration
#
logger:
  default: info
  logs:
    custom_components.my_platform: debug

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
