title: Home
resources:
  - url: /local/button-card.js
    type: module
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.keiran
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.tv_backlight
          - light.other_strip
          - group.all_leds
          - light.demo_light
        title: Lights
      - type: horizontal-stack
        title: Big TV
        cards:
        - type: entity-button
          entity: script.turn_big_tv_on_off
          show_name: false
          icon: mdi:power
          icon_height: 48px
          tap_action:
              action: call-service
              service: script.turn_big_tv_on_off
        - type: entity-button
          entity: script.turn_big_tv_volume_up
          show_name: false
          icon: mdi:volume-plus
          icon_height: 48px
          tap_action:
              action: call-service
              service: script.turn_big_tv_volume_up
        - type: entity-button
          entity: script.turn_big_tv_volume_down
          show_name: false
          icon: mdi:volume-minus
          icon_height: 48px
          tap_action:
              action: call-service
              service: script.turn_big_tv_volume_down
      - type: media-control
        entity: media_player.big_tv
      - type: horizontal-stack
        title: Mood
        cards:
        - type: "custom:button-card"
          entity: script.theme_red
          name: Red
          icon: mdi:heart
          icon_height: 48px
          state:
            - value: "off"
              color: "var(--gruvbox-red)"
          tap_action:
              action: call-service
              service: script.theme_red
        - type: "custom:button-card"
          entity: script.theme_green
          name: Green
          icon: mdi:leaf
          icon_height: 48px
          state:
            - value: "off"
              color: "var(--gruvbox-green)"
          tap_action:
              action: call-service
              service: script.theme_green
        - type: "custom:button-card"
          entity: script.theme_blue
          name: Blue
          icon: mdi:water
          icon_height: 48px
          state:
            - value: "off"
              color: "var(--gruvbox-blue)"
          tap_action:
              action: call-service
              service: script.theme_blue
      - type: horizontal-stack
        cards:
        - type: "custom:button-card"
          entity: script.theme_purple
          name: Purple
          icon: mdi:auto-fix
          icon_height: 48px
          state:
            - value: "off"
              color: "var(--gruvbox-purple)"
          tap_action:
              action: call-service
              service: script.theme_purple
        - type: "custom:button-card"
          entity: script.theme_sky
          name: Sky
          icon: mdi:apple-icloud
          icon_height: 48px
          state:
            - value: "off"
              color: "#83a598"
          tap_action:
              action: call-service
              service: script.theme_sky
        - type: "custom:button-card"
          entity: script.theme_sun
          name: Sun
          icon: mdi:white-balance-sunny
          icon_height: 48px
          state:
            - value: "off"
              color: "var(--gruvbox-yellow)"
          tap_action:
              action: call-service
              service: script.theme_sun
      - type: horizontal-stack
        title: Bedtime
        cards:
        - type: entity-button
          entity: script.go_to_bed
          name: Sleep
          icon: mdi:sleep
          icon_height: 48px
          tap_action:
              action: call-service
              service: script.go_to_bed
      - type: horizontal-stack
        title: Climate
        cards:
        - type: sensor
          entity: sensor.lumi_temperature
          name: Temperature
          graph: line
        - type: sensor
          entity: sensor.lumi_humidity
          name: Humidity
          graph: line
      - type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - automation.turn_on_after_motion
          - automation.turn_off_after_no_motion
          - automation.tv_flash
          - automation.piano_flash
        title: Automation
  - path: other_view
    title: Other
    badges:
    cards:
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.turn_on_tv_backlight
          - script.turn_off_tv_backlight
          - script.go_to_bed
          - script.turn_big_tv_on_off
          - script.turn_big_tv_volume_up
          - script.turn_big_tv_volume_down
          # - script.turn_tv_on_off
          # - script.turn_tv_volume_up
          # - script.turn_tv_volume_down
      - type: entities
        title: Learn Remote
        show_header_toggle: false
        entities:
          - script.learn_big_tv_power
          - script.learn_big_tv_volume_up
          - script.learn_big_tv_volume_down
          # - script.learn_tv_power
          # - script.learn_tv_volume_up
          # - script.learn_tv_volume_down
