title: Home
resources:
  - url: /local/button-card.js
    type: module
  - url: /local/mini-graph-card.js
    type: module
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.keiran
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.tv_backlight
          - light.other_strip
          - group.all_leds
          - light.demo_light
        title: Lights
      - type: horizontal-stack
        title: Big TV
        cards: !include lovelace/tv.yaml
      - type: media-control
        entity: media_player.big_tv
      - type: vertical-stack
        title: Actions
        cards:
        - type: "custom:button-card"
          entity: script.turn_big_tv_on_off
          name: TV
          show_name: false
          icon: mdi:television-classic
          icon_height: 48px
          aspect_ratio: 1/0.24
          tap_action:
              action: call-service
              service: script.turn_big_tv_on
        - type: "custom:button-card"
          entity: script.go_to_bed
          name: Sleep
          show_name: false
          icon: mdi:sleep
          icon_height: 48px
          aspect_ratio: 1/0.24
          tap_action:
              action: call-service
              service: script.go_to_bed
      - type: vertical-stack
        title: Mood
        cards: !include lovelace/moods.yaml
      - type: horizontal-stack
        title: Climate
        cards:
        - type: custom:mini-graph-card
          line_color: "var(--accent-color)"
          entities:
            - entity: sensor.lumi_temperature
              name: Temperature
        - type: custom:mini-graph-card
          line_color: "var(--accent-color)"
          entities:
            - entity: sensor.lumi_humidity
              name: Humidity
      - type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - automation.turn_on_after_motion
          - automation.turn_off_after_no_motion
          - automation.tv_flash
          - automation.piano_flash
        title: Automation
  - path: other_view
    title: Other
    badges:
    cards:
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.turn_on_tv_backlight
          - script.turn_off_tv_backlight
          - script.go_to_bed
          - script.turn_big_tv_on_off
          - script.turn_big_tv_volume_up
          - script.turn_big_tv_volume_down
          # - script.turn_tv_on_off
          # - script.turn_tv_volume_up
          # - script.turn_tv_volume_down
      - type: entities
        title: Learn Remote
        show_header_toggle: false
        entities:
          - script.learn_big_tv_power
          - script.learn_big_tv_volume_up
          - script.learn_big_tv_volume_down
          # - script.learn_tv_power
          # - script.learn_tv_volume_up
          # - script.learn_tv_volume_down
