title: Home
resources:
  - url: /local/button-card.js
    type: module
  - url: /local/mini-graph-card.js
    type: module
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.keiran
      - entity: media_player.big_tv_android
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.tv_backlight
          - light.other_strip
          - group.all_leds
          - light.demo_light
        title: Lights
      - type: horizontal-stack
        title: Big TV
        cards: !include lovelace/tv.yaml
      - type: media-control
        entity: media_player.big_tv_android
      - type: media-control
        entity: media_player.big_tv
      - type: vertical-stack
        title: Actions
        cards: !include lovelace/actions.yaml
      - type: vertical-stack
        title: Mood
        cards: !include lovelace/moods.yaml
      - type: vertical-stack
        title: Effects
        cards: !include lovelace/effects.yaml
      - type: horizontal-stack
        title: Climate
        cards:
        - type: custom:mini-graph-card
          line_color: "var(--accent-color)"
          entities:
            - entity: sensor.lumi_temperature
              name: Temperature
        - type: custom:mini-graph-card
          line_color: "var(--accent-color)"
          entities:
            - entity: sensor.lumi_humidity
              name: Humidity
      - type: horizontal-stack
        title: Internet
        cards:
        - type: custom:mini-graph-card
          line_color:
            - "var(--google-green-500)"
            - "var(--google-purple-500)"
            - "var(--google-yellow-500)"
          entities:
            - entity: sensor.speedtest_download
              name: Download
            - entity: sensor.speedtest_upload
              name: Upload
            - entity: sensor.speedtest_ping
              name: Ping
      - type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - automation.turn_on_after_motion
          - automation.turn_off_after_no_motion
          - automation.tv_flash
          - automation.piano_flash
        title: Automation
  - path: more_view
    title: More
    badges:
      - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_59a96004_ias_zone
      - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_59a96004_occupancy
      - entity: binary_sensor.lumi_extra_motion
        name: Second Motion
      - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_caab1f04_occupancy
        name: Second Occupancy
    cards:
      - type: entities
        title: Motion
        show_header_toggle: false
        entities:
          - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_59a96004_ias_zone
            name: Motion
          - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_59a96004_occupancy
            name: Occupancy
      - type: entities
        title: Second Motion
        show_header_toggle: false
        entities:
          - entity: binary_sensor.lumi_extra_motion
            name: Second Motion
          - entity: binary_sensor.lumi_lumi_sensor_motion_aq2_caab1f04_occupancy
            name: Second Occupancy
      - type: entities
        title: Speakers
        show_header_toggle: false
        entities:
          - media_player.family_room_speaker
          - media_player.downstairs_speaker
          - media_player.all_speakers

  - path: effects_view
    title: Effects
    icon: mdi:palette
    badges:
    cards:
      - type: entities
        entities:
          - input_boolean.colour_red
          - input_boolean.colour_green
          - input_boolean.colour_blue
          - input_boolean.colour_purple
          - input_boolean.colour_sky
          - input_boolean.colour_sun
        title: Effect Colours
  - path: scripts_view
    title: Scripts
    icon: mdi:script-text
    badges:
    cards:
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.turn_on_tv_backlight
          - script.turn_off_tv_backlight
          - script.go_to_bed
          - script.turn_big_tv_on_off
          - script.turn_big_tv_volume_up
          - script.turn_big_tv_volume_down
          # - script.turn_tv_on_off
          # - script.turn_tv_volume_up
          # - script.turn_tv_volume_down
      - type: entities
        title: Learn Remote
        show_header_toggle: false
        entities:
          - script.learn_big_tv_power
          - script.learn_big_tv_volume_up
          - script.learn_big_tv_volume_down
          # - script.learn_tv_power
          # - script.learn_tv_volume_up
          # - script.learn_tv_volume_down
