type: entities
title: Automation
entities:
  - automation.notify_motion
  - automation.turn_on_after_motion
  - automation.turn_off_after_no_motion
  - automation.tv_flash
  - automation.piano_flash

