#
# Colours used in effects
#
input_boolean:
   deck_lights:
     name: Deck lights
     initial: off
   effect_running:
     name: Effect running
     initial: off
   colour_red:
     name: Red
     icon: mdi:invert-colors
     initial: off
   colour_green:
     name: Green
     icon: mdi:invert-colors
     initial: off
   colour_blue:
     name: Blue
     icon: mdi:invert-colors
     initial: on
   colour_purple:
     name: Purple
     icon: mdi:invert-colors
     initial: on
   colour_sky:
     name: Sky
     icon: mdi:invert-colors
     initial: on
   colour_sun:
     name: Sun
     icon: mdi:invert-colors
     initial: off

#
# Connect deck light input_boolean to iftt
#
automation:
  - alias: Turn on deck lights
    trigger:
      - platform: state
        entity_id: input_boolean.deck_lights
        to: 'on'
    action:
      - service: script.turn_on_deck_lights
  - alias: Turn off deck lights
    trigger:
      - platform: state
        entity_id: input_boolean.deck_lights
        to: 'off'
    action:
      - service: script.turn_off_deck_lights

#
# Lighting scripts
#
script: !include_dir_merge_named scripts

#
# Deck light icon
#
homeassistant:
  customize:
    input_boolean.deck_lights:
      icon: mdi:string-lights
