flash:
  description: Just trying out services
  fields:
    name:
      description: The name for the hello services
      example: World :)
theme:
  description: A theme for the lights
  fields:
    name:
      description: The name for the hello services
      example: World :)
