tts:
  - platform: google_translate

automation: !include ../automations.yaml
group: !include ../groups.yaml
scene: !include ../scenes.yaml
script: !include_dir_merge_named ../scripts
logger:
  default: info
  logs:
    custom_components.my_platform: debug
    custom_components.tv_service: debug
