#
# SSL
#
http:
  server_port: !secret server_port
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

#
# Google assistant
#
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include ../google-service-account.json
  exposed_domains:
    - sensor
    - light
    - script
    - scene

#
# Speedtest.net
#
speedtestdotnet:
  scan_interval:
    hours: 12
  monitored_conditions:
    - ping
    - download
    - upload

#
# Sound on boot
#
automation:
  - id: on_hass_boot
    alias: On Boot
    description: ''
    trigger:
    - event: start
      platform: homeassistant
    condition: []
    action:
    - data:
        entity_id: media_player.family_room_speaker
        media_content_id: !secret startup_mp3_path
        media_content_type: audio/mp3
      service: media_player.play_media
  - id: notify_on_hass_update
    alias: Notify on hass update
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      - service: notify.notify
        data:
          message: 'There is a new Home Assistant release available.'
